### ISSUE TITLE
Chat Archive - App crash

### ISSUE THREAD

**Issue by KestrelKitezh** [kauffman12/EQLogParser#105]
I was trying the chat archive function to lookup a name, and no matter which logfile I load, the application just flat out crash when I click it. There are no errors in the perser.log for the current time (07:43, 16.08.2023),  but there is another error in here from yesterday which I might aswell paste in case.

> 2023-08-15 15:46:30,016 [13] ERROR EQLogParser.MiscLineParser - System.ArgumentException: Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at System.Collections.Generic.List`1.CopyTo(T[] array, Int32 arrayIndex)
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EQLogParser.MainActions.<>c.<InitVerifiedPlayers>b__17_1(Object name, String playerClass)
   at EQLogParser.PlayerManager.SetPlayerClass(String player, SpellClass theClass, String reason)
   at EQLogParser.MiscLineParser.Process(LineData lineData)

**Comment by KestrelKitezh** [comment]
[EQLogParser.log](https://github.com/kauffman12/EQLogParser/files/12356055/EQLogParser.log)

**Comment by KestrelKitezh** [comment]
[EQLogParser.log](https://github.com/kauffman12/EQLogParser/files/12356080/EQLogParser.log)

**Comment by KestrelKitezh** [comment]
The archives with the data in the appdata folder seem fine, and nothing weird as I can see. Found the name though. Its not a huge deal, but figured I'd report it.

Thanks for the work on this app. Its great, and as a hobbyist programmer which are trying to transition from forms to wpf, its been a great learning experience reading some of the code.<3

**Comment by KestrelKitezh** [comment]
(Running 2.1.25)

**Comment by KestrelKitezh** [comment]
Kk

Renamed folder.
Turned off auto load last log
Tried the repair,

All leading to the same crash

**Comment by kauffman12** [comment]
Can you look in your Program Files\EQLogParser directory and see if any of these files are missing? Also Windows 10 or 11?

![image](https://github.com/kauffman12/EQLogParser/assets/771335/c84a14ef-036e-4e05-913f-bed588e9ff20)

**Comment by KestrelKitezh** [comment]
33 files, 2 folders.
![image](https://github.com/kauffman12/EQLogParser/assets/44786999/5a7712ee-a2ad-4d35-b3a2-7fbdd5f86f40)

Win10, even tried running it as admin in case there where some  windows stuff locking down programfiles

**Comment by kauffman12** [comment]
I just did a new install in a windows 10 VM and it works OK. It looks like you have all the right files.

Maybe put your archive back but then rename that entire directory:
AppData\Roaming\EQLogParser

Let it start over with new settings and see if it still crashes. The only other thing I guess is the version of .net 6. I was just using 6.0.21. What do you have? I could try older versions to see if there's a difference.

You can run this to see what you have:
dotnet --list-runtimes

**Comment by KestrelKitezh** [comment]
![image](https://github.com/kauffman12/EQLogParser/assets/44786999/f45cd7dd-7bfa-4285-b776-3e641d61486f)

Renaming folder now and trying

**Comment by KestrelKitezh** [comment]
Still crashes

**Comment by kauffman12** [comment]
No I think 6.0.11 is fine. You could try getting the latest if you want.
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.21-windows-x64-installer

I also uploaded a 2.1.26 with some extra error handling. Nothing major though but it's worth a try. If that doesn't work I'll need a debug build just for you to run with some extra logging.

**Comment by KestrelKitezh** [comment]
2.1.26 is the same, and error log is just load data

**Comment by kauffman12** [comment]
Does the Log Search work? They do a lot of similar things.

**Comment by kauffman12** [comment]
Also try this version to see what ends up in the error log. Just open chat archive one and let it crash and send what it added.

https://github.com/kauffman12/EQLogParser/raw/master/Release/Debug/EQLogParser.msi

**Comment by kauffman12** [comment]
Looking again at your screenshot. What language and region type settings are you using? I noticed the date format on your files isn't the typical US format. And are there additional fonts installed?

**Comment by KestrelKitezh** [comment]
Running English Windows with Norwegian time/date format. No fonts

**Comment by KestrelKitezh** [comment]
2023-08-19 15:27:26,083 [1] INFO EQLogParser.MainWindow - Initialized Components
2023-08-19 15:27:26,827 [1] WARN EQLogParser.MainActions - Returning 7 opened Windows
2023-08-19 15:27:32,329 [1] INFO EQLogParser.MainWindow - Selected Log File: F:\Games\Everquest\Logs\eqlog_REDACTED_oakwynd.txt
2023-08-19 15:27:33,632 [1] INFO EQLogParser.MainWindow - Finished Loading Log File in 1 seconds.
2023-08-19 15:27:33,830 [1] WARN EQLogParser.MainActions - Returning 8 opened Windows
2023-08-19 15:27:33,841 [1] WARN EQLogParser.MainActions - Returning 8 opened Windows
2023-08-19 15:27:33,841 [1] WARN EQLogParser.MainActions - Returning 8 opened Windows
2023-08-19 15:27:33,842 [1] WARN EQLogParser.MainActions - Returning 8 opened Windows
2023-08-19 15:27:37,138 [1] WARN EQLogParser.MainActions - Returning 8 opened Windows
2023-08-19 15:27:37,139 [1] WARN EQLogParser.MainActions - Returning 8 opened Windows
2023-08-19 15:27:37,139 [1] WARN EQLogParser.MainActions - Returning 8 opened Windows
2023-08-19 15:28:01,944 [1] WARN EQLogParser.MainActions - Returning 8 opened Windows
2023-08-19 15:28:01,944 [1] WARN EQLogParser.MainActions - Returning 8 opened Windows
2023-08-19 15:28:01,945 [1] WARN EQLogParser.MainActions - Returning 8 opened Windows
2023-08-19 15:28:02,942 [1] WARN EQLogParser.MainActions - Returning 8 opened Windows
2023-08-19 15:28:03,856 [1] WARN EQLogParser.MainWindow - Open Chat Archive Window
2023-08-19 15:28:03,856 [1] WARN EQLogParser.MainActions - Reading Docked Windows
2023-08-19 15:28:03,857 [1] WARN EQLogParser.MainActions - playerParseTextWindow
2023-08-19 15:28:03,857 [1] WARN EQLogParser.MainActions - Reading Docked Windows
2023-08-19 15:28:03,857 [1] WARN EQLogParser.MainActions - triggerLogWindow
2023-08-19 15:28:03,857 [1] WARN EQLogParser.MainActions - Reading Docked Windows
2023-08-19 15:28:03,857 [1] WARN EQLogParser.MainActions - triggerTestWindow
2023-08-19 15:28:03,858 [1] WARN EQLogParser.MainActions - Reading Docked Windows
2023-08-19 15:28:03,858 [1] WARN EQLogParser.MainActions - npcWindow
2023-08-19 15:28:03,858 [1] WARN EQLogParser.MainActions - Reading Docked Windows
2023-08-19 15:28:03,858 [1] WARN EQLogParser.MainActions - petMappingWindow
2023-08-19 15:28:03,858 [1] WARN EQLogParser.MainActions - Reading Docked Windows
2023-08-19 15:28:03,859 [1] WARN EQLogParser.MainActions - verifiedPlayersWindow
2023-08-19 15:28:03,859 [1] WARN EQLogParser.MainActions - Reading Docked Windows
2023-08-19 15:28:03,859 [1] WARN EQLogParser.MainActions - verifiedPetsWindow
2023-08-19 15:28:03,859 [1] WARN EQLogParser.MainActions - Reading Docked Windows
2023-08-19 15:28:03,860 [1] WARN EQLogParser.MainActions - damageSummaryWindow
2023-08-19 15:28:03,860 [1] WARN EQLogParser.MainActions - Returning 8 opened Windows
2023-08-19 15:28:03,860 [1] WARN EQLogParser.Helpers - Check if Window needs to be closed
2023-08-19 15:28:03,860 [1] WARN EQLogParser.Helpers - Create Window Instance
2023-08-19 15:28:04,006 [1] WARN EQLogParser.Helpers - Create Control
2023-08-19 15:28:04,006 [1] WARN EQLogParser.Helpers - Update Dock Manager
2023-08-19 15:28:04,006 [1] WARN EQLogParser.Helpers - Set Window Content
2023-08-19 15:28:04,007 [1] WARN EQLogParser.Helpers - BeginInit on DockSite
2023-08-19 15:28:04,007 [1] WARN EQLogParser.Helpers - Add Child to DockSite
2023-08-19 15:28:04,020 [1] WARN EQLogParser.Helpers - EndInit
2023-08-19 15:28:04,020 [1] WARN EQLogParser.Helpers - Complete
2023-08-19 15:28:14,405 [1] INFO EQLogParser.MainWindow - Initialized Components
2023-08-19 15:28:15,029 [1] WARN EQLogParser.MainActions - Returning 7 opened Windows

**Comment by kauffman12** [comment]
Thanks. I'm testing with those settings and others to see if I can reproduce the crash. So far I haven't although I found another unrelated problem I have to fix..

And here try this one. The log you just sent looks good so the problem must  be in the chat component itself.

https://github.com/kauffman12/EQLogParser/raw/master/Release/Debug/EQLogParser-2.msi

**Comment by KestrelKitezh** [comment]
2023-08-19 22:06:33,598 [1] INFO EQLogParser.MainWindow - Using DotNet 6.0.21
2023-08-19 22:06:36,609 [1] INFO EQLogParser.MainWindow - Initialized Components
2023-08-19 22:07:41,315 [1] INFO EQLogParser.MainWindow - Selected Log File: F:\Games\Everquest\Logs\eqlog_REDACTED_oakwynd.txt
2023-08-19 22:07:41,583 [1] INFO EQLogParser.MainWindow - Finished Loading Log File in 0 seconds.
2023-08-19 22:07:47,529 [1] INFO EQLogParser.MainWindow - Selected Log File: F:\Games\Everquest\Logs\eqlog_REDACTED_oakwynd.txt
2023-08-19 22:07:58,107 [1] INFO EQLogParser.MainWindow - Finished Loading Log File in 11 seconds.
2023-08-19 22:08:08,952 [1] WARN EQLogParser.ChatViewer - ChatView Init1
2023-08-19 22:08:08,981 [1] WARN EQLogParser.ChatViewer - Init1 Complete
2023-08-19 22:08:08,990 [1] WARN EQLogParser.ChatViewer - Get System Fonts
2023-08-19 22:08:08,994 [1] WARN EQLogParser.Helpers - Found 78 Fonts
2023-08-19 22:08:08,995 [1] WARN EQLogParser.ChatViewer - Fonts Loaded
2023-08-19 22:08:08,995 [1] WARN EQLogParser.ChatViewer - Set startDate
2023-08-19 22:08:09,001 [1] WARN EQLogParser.ChatViewer - Change Search Called
2023-08-19 22:08:09,001 [1] WARN EQLogParser.ChatViewer - Set endDate
2023-08-19 22:08:09,001 [1] WARN EQLogParser.ChatViewer - Change Search Called
2023-08-19 22:08:09,004 [1] WARN EQLogParser.ChatViewer - Read Selected Font
2023-08-19 22:08:09,004 [1] WARN EQLogParser.ChatViewer - Selected = 
2023-08-19 22:08:09,007 [1] WARN EQLogParser.ChatViewer - Set selected font
2023-08-19 22:08:09,007 [1] WARN EQLogParser.ChatViewer - Read Font Size
2023-08-19 22:08:09,007 [1] WARN EQLogParser.ChatViewer - Size = 
2023-08-19 22:08:09,008 [1] WARN EQLogParser.ChatViewer - Update Text Color
2023-08-19 22:08:09,008 [1] WARN EQLogParser.ChatViewer - Default Color = #DDFFFFFF
2023-08-19 22:08:09,009 [1] WARN EQLogParser.ChatViewer - Color Theme Setting = ChatFontFgColorMaterialDark
2023-08-19 22:08:09,009 [1] WARN EQLogParser.ChatViewer - Read Color Setting = #DDFFFFFF
2023-08-19 22:08:09,010 [1] WARN EQLogParser.ChatViewer - Updated ColorPicker
2023-08-19 22:08:09,010 [1] WARN EQLogParser.ChatViewer - Create FilterTimer
2023-08-19 22:08:09,010 [1] WARN EQLogParser.ChatViewer - Load Players
2023-08-19 22:08:09,011 [1] WARN EQLogParser.ChatViewer - updatedPlayer = 
2023-08-19 22:08:09,011 [1] WARN EQLogParser.ChatViewer - Get Archived Players
2023-08-19 22:08:09,012 [1] WARN EQLogParser.ChatViewer - There were 2 System.Windows.Controls.ComboBox Items.Count:1
2023-08-19 22:08:09,012 [1] WARN EQLogParser.ChatViewer - Update ItemsSource
2023-08-19 22:08:09,013 [1] WARN EQLogParser.ChatViewer - Read Selected Player Setting
2023-08-19 22:08:09,013 [1] WARN EQLogParser.ChatViewer - Selected Player = 
2023-08-19 22:08:09,013 [1] WARN EQLogParser.ChatViewer - Set player to current user as default
2023-08-19 22:08:09,013 [1] WARN EQLogParser.ChatViewer - Updated PlayerList
2023-08-19 22:08:09,014 [1] WARN EQLogParser.ChatViewer - Selected In List
2023-08-19 22:08:09,016 [1] WARN EQLogParser.ChatViewer - Selection Worked
2023-08-19 22:08:09,016 [1] WARN EQLogParser.ChatViewer - Setting Ready
2023-08-19 22:08:09,017 [1] WARN EQLogParser.ChatViewer - Added Event Handlers
2023-08-19 22:08:09,017 [1] WARN EQLogParser.ChatViewer - Created Update Search Task
2023-08-19 22:08:17,195 [1] INFO EQLogParser.MainWindow - Using DotNet 6.0.21
2023-08-19 22:08:19,068 [1] INFO EQLogParser.MainWindow - Initialized Components

**Comment by kauffman12** [comment]
Thanks and so far this is kinda confusing. Everything seems fine so far... But got one more important part to check where an exception might get hidden.

Hopefully this will be the last one.

https://github.com/kauffman12/EQLogParser/raw/master/Release/Debug/EQLogParser-3.msi

**Comment by KestrelKitezh** [comment]
2023-08-19 23:04:31,351 [1] INFO EQLogParser.MainWindow - Using DotNet 6.0.21
2023-08-19 23:04:33,896 [1] INFO EQLogParser.MainWindow - Initialized Components
2023-08-19 23:04:45,033 [1] INFO EQLogParser.MainWindow - Selected Log File: F:\Games\Everquest\Logs\eqlog_REDACTED_oakwynd.txt
2023-08-19 23:04:55,105 [1] INFO EQLogParser.MainWindow - Finished Loading Log File in 10 seconds.
2023-08-19 23:05:01,185 [1] WARN EQLogParser.ChatViewer - ChatView Init1
2023-08-19 23:05:01,226 [1] WARN EQLogParser.ChatViewer - Get System Fonts
2023-08-19 23:05:01,230 [1] WARN EQLogParser.Helpers - Found 78 Fonts
2023-08-19 23:05:01,235 [1] WARN EQLogParser.ChatViewer - Fonts Loaded
2023-08-19 23:05:01,236 [1] WARN EQLogParser.ChatViewer - Set startDate = Message Search
2023-08-19 23:05:01,241 [1] WARN EQLogParser.ChatViewer - Change Search Called
2023-08-19 23:05:01,242 [1] WARN EQLogParser.ChatViewer - Change Search Complete
2023-08-19 23:05:01,242 [1] WARN EQLogParser.ChatViewer - Set endDate = 16.03.1999 00:00:00
2023-08-19 23:05:01,243 [1] WARN EQLogParser.ChatViewer - Change Search Called
2023-08-19 23:05:01,243 [1] WARN EQLogParser.ChatViewer - Change Search Complete
2023-08-19 23:05:01,246 [1] WARN EQLogParser.ChatViewer - Read Selected Font
2023-08-19 23:05:01,247 [1] WARN EQLogParser.ChatViewer - Selected = 
2023-08-19 23:05:01,250 [1] WARN EQLogParser.ChatViewer - Set selected font to Segoe UI
2023-08-19 23:05:01,251 [1] WARN EQLogParser.ChatViewer - Update Text Color
2023-08-19 23:05:01,251 [1] WARN EQLogParser.ChatViewer - Default Color = #DDFFFFFF
2023-08-19 23:05:01,251 [1] WARN EQLogParser.ChatViewer - Color Theme Setting = ChatFontFgColorMaterialDark
2023-08-19 23:05:01,251 [1] WARN EQLogParser.ChatViewer - Read Color Setting = #DDFFFFFF
2023-08-19 23:05:01,252 [1] WARN EQLogParser.ChatViewer - Updated ColorPicker
2023-08-19 23:05:01,253 [1] WARN EQLogParser.ChatViewer - Create FilterTimer
2023-08-19 23:05:01,253 [1] WARN EQLogParser.ChatViewer - Load Players
2023-08-19 23:05:01,254 [1] WARN EQLogParser.ChatViewer - updatedPlayer = 
2023-08-19 23:05:01,254 [1] WARN EQLogParser.ChatViewer - Get Archived Players
2023-08-19 23:05:01,255 [1] WARN EQLogParser.ChatViewer - There were 2 System.Windows.Controls.ComboBox Items.Count:1
2023-08-19 23:05:01,255 [1] WARN EQLogParser.ChatViewer - Update ItemsSource
2023-08-19 23:05:01,256 [1] WARN EQLogParser.ChatViewer - Read Selected Player Setting
2023-08-19 23:05:01,256 [1] WARN EQLogParser.ChatViewer - Selected Player = 
2023-08-19 23:05:01,256 [1] WARN EQLogParser.ChatViewer - Set player to current user as default
2023-08-19 23:05:01,256 [1] WARN EQLogParser.ChatViewer - Updated PlayerList
2023-08-19 23:05:01,257 [1] WARN EQLogParser.ChatViewer - Selected In List
2023-08-19 23:05:01,259 [1] WARN EQLogParser.ChatViewer - Selection Worked
2023-08-19 23:05:01,259 [1] WARN EQLogParser.ChatViewer - Setting Ready
2023-08-19 23:05:01,260 [1] WARN EQLogParser.ChatViewer - Added Event Handlers
2023-08-19 23:05:01,260 [1] WARN EQLogParser.ChatViewer - Created Update Search Task
2023-08-19 23:05:05,100 [19] WARN EQLogParser.ChatViewer - Update Search Tasking Running. Calling Dispatcher
2023-08-19 23:05:08,610 [1] INFO EQLogParser.MainWindow - Using DotNet 6.0.21
2023-08-19 23:05:10,531 [1] INFO EQLogParser.MainWindow - Initialized Components

**Comment by KestrelKitezh** [comment]
I still stand by my previous statement though. If I'm the only one that got this atm, your time must be better spent elsewhere

**Comment by kauffman12** [comment]
Well I'm sure someone else will run into something similar eventually. There's no reason this shouldn't work. It's not doing anything that complicated.

One main difference is my system has 187 fonts and yours is returning 78. I'm defaulting to Segoe UI if no preferences are saved yet and the crash seems to happen outside the main thread that I have any control over.. So possible after an event is thrown from my updating a control with selected values/defaults. 

If you bring up Windows Control Panel -> Fonts do you see Segoe UI in the list? Maybe I'm trying to set a font that doesn't exist and that blows up.

![image](https://github.com/kauffman12/EQLogParser/assets/771335/92e09626-e2d7-4fef-9602-6dc407e11c40)

**Comment by kauffman12** [comment]
So my two guesses are the missing Font issue and possibly somehow using a Dispatcher too early from another thread. I added a check for the Font and removed the extra thread just to see what happens. Here's one more build. If this doesn't help maybe I can make an easy to run project you can play in visual studio. I'm sure it would break at the right spot if run in debug mode.

https://github.com/kauffman12/EQLogParser/raw/master/Release/Debug/EQLogParser-4.msi

**Comment by KestrelKitezh** [comment]
![image](https://github.com/kauffman12/EQLogParser/assets/44786999/13954911-5fb9-4dcf-bf8b-28e34862e70d)

**Comment by KestrelKitezh** [comment]
2023-08-20 09:52:09,341 [1] INFO EQLogParser.MainWindow - Using DotNet 6.0.21
2023-08-20 09:52:12,500 [1] INFO EQLogParser.MainWindow - Initialized Components
2023-08-20 09:52:26,261 [1] INFO EQLogParser.MainWindow - Selected Log File: F:\Games\Everquest\Logs\eqlog_REDACTED_oakwynd.txt
2023-08-20 09:52:36,259 [1] INFO EQLogParser.MainWindow - Finished Loading Log File in 10 seconds.
2023-08-20 09:52:43,223 [1] WARN EQLogParser.ChatViewer - ChatView Init1
2023-08-20 09:52:43,266 [1] WARN EQLogParser.Helpers - Found 78 Fonts
2023-08-20 09:52:43,272 [1] WARN EQLogParser.ChatViewer - Change Search Called
2023-08-20 09:52:43,273 [1] WARN EQLogParser.ChatViewer - Change Search Complete
2023-08-20 09:52:43,273 [1] WARN EQLogParser.ChatViewer - Change Search Called
2023-08-20 09:52:43,274 [1] WARN EQLogParser.ChatViewer - Change Search Complete
2023-08-20 09:52:43,278 [1] WARN EQLogParser.ChatViewer - Set selected font to Segoe UI
2023-08-20 09:52:43,280 [1] WARN EQLogParser.ChatViewer - There were 2 players
2023-08-20 09:52:43,281 [1] WARN EQLogParser.ChatViewer - Update ItemsSource
2023-08-20 09:52:43,281 [1] WARN EQLogParser.ChatViewer - Set player to current user as default
2023-08-20 09:52:43,283 [1] WARN EQLogParser.ChatViewer - Setting Ready
2023-08-20 09:52:43,283 [1] WARN EQLogParser.ChatViewer - Added Event Handlers
2023-08-20 09:52:43,284 [1] WARN EQLogParser.ChatViewer - Change Search Called
2023-08-20 09:52:43,284 [1] WARN EQLogParser.ChatViewer - Name Length long enough to not cause index problem
2023-08-20 09:52:43,284 [1] WARN EQLogParser.ChatViewer - Get Channel List
2023-08-20 09:52:43,284 [1] WARN EQLogParser.ChatViewer - List Count = 8
2023-08-20 09:52:43,285 [1] WARN EQLogParser.ChatViewer - Set Chat Filter
2023-08-20 09:52:43,285 [1] WARN EQLogParser.ChatViewer - Update Iterator
2023-08-20 09:52:43,287 [1] WARN EQLogParser.ChatViewer - Changed? = True
2023-08-20 09:52:43,287 [1] WARN EQLogParser.ChatViewer - Save Selected Channels
2023-08-20 09:52:43,287 [1] WARN EQLogParser.ChatViewer - Channels Saved
2023-08-20 09:52:43,288 [1] WARN EQLogParser.ChatViewer - Display Page
2023-08-20 09:52:43,296 [1] WARN EQLogParser.ChatViewer - Change Search Complete
2023-08-20 09:52:51,499 [1] INFO EQLogParser.MainWindow - Using DotNet 6.0.21
2023-08-20 09:52:53,507 [1] INFO EQLogParser.MainWindow - Initialized Components

**Comment by kauffman12** [comment]
That actually looks good... I guess the problem must be in one of the Syncfusion components. 

What happens if you bring up View -> Triggers -> Trigger Tester? It also uses EditControl like Log Search and Chat but doesn't use some of the other components.

**Comment by kauffman12** [comment]
Here's a build with some updated Syncfusion libraries on the off chance they fixed a bug.

https://github.com/kauffman12/EQLogParser/raw/master/Release/Debug/EQLogParser-5.msi

**Comment by kauffman12** [comment]
Actually I finally got a crash to happen once and I made some fixes for that. Plus I included the new syncfusion in the normal build.

Try the regular 2.1.28 and see if that's any better. If not I'll zip up a cleaned up parser for you try try from Visual Studio. All it should need is WPF development tools which you probably have already.

**Comment by KestrelKitezh** [comment]
That did it. Great work :D

**Comment by kauffman12** [comment]
Nice! If you have time try some other windows you may not have used before or often. Just to see if anything else crashes. For whatever reason your system may be good to test with.

**Comment by KestrelKitezh** [comment]
Tried em all. All worked

**Comment by kauffman12** [comment]
Awesome. Thanks!
