### ISSUE TITLE
Crash on startup (locale issue?)

### ISSUE THREAD

**Issue by moritzmacke** [kauffman12/EQLogParser#126]
There seems to be an issue causing the window width to be read incorrectly from settings.txt making the app crash on startup. 

from log:
2023-11-15 15:58:45,379 [1] ERROR EQLogParser.MainWindow - System.ArgumentException: "9944000000000000" ist kein gültiger Wert für diese Eigenschaft. Gültige Werte reichen von "Int32.MinValue" bis "Int32.MaxValue".
   (...)
   at System.Windows.FrameworkElement.set_Width(Double value)
   at EQLogParser.MainWindow..ctor()

line in settings:
WindowWidth=994.4000000000001

I suspect it's because my computer's locale is German which uses ',' as decimal separator not a dot (which is ignored).

**Comment by kauffman12** [comment]
Does it work if you change the 994.4000000000001 to just 994?

**Comment by moritzmacke** [comment]
> Does it work if you change the 994.4000000000001 to just 994?

Yes, or replacing the '.' with ',' also works, but only temporarily as the settings file is overwritten every time the program runs. 
Seems like when parsing the input it uses local format, but output defaults to English format.

**Comment by moritzmacke** [comment]
Yeah, I think I found the problem:

MainWindow : ConfigUtil.SetSetting("WindowWidth", Width.ToString(CultureInfo.InvariantCulture));
-> invariant culture is set for toString()

ConfigUtil : double.TryParse(GetSetting(key), out var result)
-> no number format set, defaults to one of current culture

**Comment by kauffman12** [comment]
Yeah. Try 2.1.52. I think it should handle it now.

**Comment by moritzmacke** [comment]
Works now. Perfect, thanks!

**Comment by moritzmacke** [comment]
Sorry, only just noticed the damage overlay window has the same problem. In DamageOverlayWindow.SetWindowSizes() there are another 4 instances of double.TryParse() that don't set the culture. This causes the window to disappear off-screen or, if the resulting values are very large, crashes the program with the same exception mentioned before. Might want to go over all occurrences of double.TryParse() in the program to see whether the problem could crop up elsewhere.

**Comment by kauffman12** [comment]
Try 2.1.54.

**Comment by moritzmacke** [comment]
Used it for a while today, moving/resizing the overlay now and then and restarting the program several times with no problem. So I can report that it works correctly now, thank you!

**Comment by kauffman12** [comment]
No prob.
