### ISSUE TITLE
Log parser wont load

### ISSUE THREAD

**Issue by Eqerer** [kauffman12/EQLogParser#142]
Im running into an issue when i load eq parser. i get no errors, but the program wont launch. i can see it goes to the task bar but then closes without a visible error. 

I have windows 11, i have installed and uninstalled and reinstalled .Net 6.0 Desktop Runtime for x64 multiple times. the error windows gives me in the logs is below and i cant tell if its from eqlogparser or something on my side. 

Application: EQLogParser.exe
CoreCLR Version: 6.0.2123.36311
.NET Version: 6.0.21
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at Syncfusion.Windows.Tools.Controls.TDILayoutPanel.UpdateVisualTree(DocumentTabControl tabControl)
   at Syncfusion.Windows.Tools.Controls.TDILayoutPanel.OnItemsChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Syncfusion.Windows.Tools.Controls.TabControlExt.OnItemsChanged(NotifyCollectionChangedEventArgs e)
   at Syncfusion.Windows.Tools.Controls.DocumentTabControl.OnItemsChanged(NotifyCollectionChangedEventArgs e)
   at System.Windows.Controls.ItemsControl.OnItemCollectionChanged2(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Windows.Data.CollectionView.OnCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Windows.Controls.ItemCollection.OnViewCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   at System.Windows.WeakEventManager.DeliverEvent(Object sender, EventArgs args)
   at System.Collections.Specialized.CollectionChangedEventManager.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Windows.Data.CollectionView.OnCollectionChanged(NotifyCollectionChangedEventArgs args)
   at MS.Internal.Controls.InnerItemCollectionView._RemoveAt(Int32 index, Int32 indexR, Object item)
   at MS.Internal.Controls.InnerItemCollectionView.RemoveAt(Int32 index)
   at System.Windows.Controls.ItemCollection.RemoveAt(Int32 removeIndex)
   at Syncfusion.Windows.Tools.Controls.DocumentTabControl.UpdateIndex(Int32 index, FrameworkElement element)
   at Syncfusion.Windows.Tools.Controls.TDILayoutPanel.SetTDIIndexForDocking(FrameworkElement element)
   at Syncfusion.Windows.Tools.Controls.TDILayoutPanel.TDILayoutPanel_Loaded(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.HwndSubclass.DefWndProcWrapper(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

i was using logparser just fine a week ago and now im cant see anything and its driving me crazy.

**Comment by kauffman12** [comment]
Try deleting the dockSite.xml that stores the windows you had opened last.
It's in AppData:

C:\Users\username\AppData\Roaming\EQLogParser\config\dockSite.xml

**Comment by Eqerer** [comment]
> Try deleting the dockSite.xml that stores the windows you had opened last. It's in AppData: C:\Users\username\AppData\Roaming\EQLogParser\config\dockSite.xml


This took care of it. 

Thank you much for your quick reply and support.

**Comment by kauffman12** [comment]
No prob. I may make  bug report for that with the product I'm using. That really shouldn't happen.
