### ISSUE TITLE
Exception recorded in EQLogParser.log

### ISSUE THREAD

**Issue by cluefone** [kauffman12/EQLogParser#176]
I'm seeing the following in 2.2.20 when starting the app. I typically have multiple characters with active trigger monitoring, but this error occurs with any selected. The startup is clean with no characters checked in the Trigger Manager. 

2024-05-26 13:57:17,935 [1] ERROR EQLogParser.App - AppDispatcherUnhandledException
2024-05-26 13:57:17,936 [1] ERROR EQLogParser.App - Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at EQLogParser.TriggersCharacterView.RefreshData()
   at EQLogParser.TriggersCharacterView.UpdateStatus()
   at EQLogParser.TriggersCharacterView.StatusTimerTick(Object sender, EventArgs e)
   at System.Windows.Threading.DispatcherTimer.FireTick()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by kauffman12** [comment]
Do you leave Trigger Manager open when you close the app? Just curious.

**Comment by SilvenaRogue** [comment]
Not OP

I had that same thing pop in my error log (posted in my report about being You in the archived log)
I always leave Trigger Manager open when closing the app.

**Comment by cluefone** [comment]
Yes, I always keep the Trigger Manager open. I don't close anything manually, and it is one of the tabs that persists through a restart.

**Comment by kauffman12** [comment]
Ok. Yeah it's probably just a timing issue. The window is loading slowly on some systems. After the log readers are already sending status. I'll put in some extra checks for that. It shouldn't be a big issue.

**Comment by kauffman12** [comment]
Try 2.2.21 to see if these go away.
