### ISSUE TITLE
Unable to play sound no audio device

### ISSUE THREAD

**Issue by vapourized** [kauffman12/EQLogParser#202]
I have reinstalled my sound drive on windows 11.  I do have sound in everything else but log parser.  I have went into system sound mixer and verified Realtek is selected and still get the unable to play error in parser.  Any ideas of what could be the issue?

**Comment by vapourized** [comment]
***@***.***


***@***.***


2024-08-20 17:02:07,668 [1] INFO EQLogParser.App - EQLogParser: 2.2.43, DotNet: 8.0.5
2024-08-20 17:02:07,971 [1] INFO EQLogParser.MainWindow - Window Pos (155, 3)
2024-08-20 17:02:07,971 [1] INFO EQLogParser.MainWindow - Window Size (1920, 811)
2024-08-20 17:02:14,227 [8] INFO EQLogParser.MainWindow - Selected Log File: C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\Logs\eqlog_Vaporizedx_xegony.txt
2024-08-20 17:02:15,863 [1] INFO EQLogParser.AudioManager - Init Audio
2024-08-20 17:02:15,864 [1] INFO EQLogParser.AudioManager - Init using -1
2024-08-20 17:02:15,872 [1] ERROR EQLogParser.AudioManager - Audio Exception
NAudio.MmException: BadDeviceId calling waveOutOpen
   at NAudio.MmException.Try(MmResult result, String function)
   at NAudio.Wave.WaveOutEvent.Init(IWaveProvider waveProvider)
   at EQLogParser.AudioManager.InitAudio()
2024-08-20 17:02:15,931 [1] WARN EQLogParser.AudioManager - No audio device found!
2024-08-20 17:02:16,103 [1] INFO EQLogParser.MainWindow - Finished Loading Log File in 2 seconds.
2024-08-20 17:02:16,238 [1] WARN EQLogParser.TriggerProcessor - Over 513 triggers active for one character. To improve performance consider turning off old triggers.
2024-08-20 17:02:23,477 [1] INFO EQLogParser.AudioManager - Init Audio
2024-08-20 17:02:23,478 [1] INFO EQLogParser.AudioManager - Init using -1
2024-08-20 17:02:23,478 [1] ERROR EQLogParser.AudioManager - Audio Exception
NAudio.MmException: BadDeviceId calling waveOutOpen
   at NAudio.MmException.Try(MmResult result, String function)
   at NAudio.Wave.WaveOutEvent.Init(IWaveProvider waveProvider)
   at EQLogParser.AudioManager.InitAudio()
2024-08-20 17:03:54,698 [1] INFO EQLogParser.AudioManager - Init Audio
2024-08-20 17:03:54,699 [1] INFO EQLogParser.AudioManager - Init using -1
2024-08-20 17:03:54,699 [1] ERROR EQLogParser.AudioManager - Audio Exception
NAudio.MmException: BadDeviceId calling waveOutOpen
   at NAudio.MmException.Try(MmResult result, String function)
   at NAudio.Wave.WaveOutEvent.Init(IWaveProvider waveProvider)
   at EQLogParser.AudioManager.InitAudio()

**Comment by kauffman12** [comment]
It seems like you don't have a default audio device somehow. Try this version. It tries to use whatever it can find if there's no default.

https://github.com/kauffman12/EQLogParser/raw/master/Release/test/EQLogParser-install-2.2.43-test2.exe

**Comment by vapourized** [comment]
This version crashes when I click on volume.


2024-08-20 19:42:11,237 [1] INFO EQLogParser.App - EQLogParser: 2.2.43, DotNet: 8.0.5
2024-08-20 19:42:11,665 [1] INFO EQLogParser.MainWindow - Window Pos (155, 3)
2024-08-20 19:42:11,666 [1] INFO EQLogParser.MainWindow - Window Size (1920, 811)
2024-08-20 19:42:20,206 [11] INFO EQLogParser.MainWindow - Selected Log File: C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\Logs\eqlog_Vaporizedx_xegony.txt
2024-08-20 19:42:21,728 [1] ERROR EQLogParser.App - AppDispatcherUnhandledException
System.IO.FileNotFoundException: Could not load file or assembly 'NAudio.WinForms, Version=2.2.1.0, Culture=neutral, PublicKeyToken=e279aa5131008a41'. The system cannot find the file specified.
File name: 'NAudio.WinForms, Version=2.2.1.0, Culture=neutral, PublicKeyToken=e279aa5131008a41'
   at EQLogParser.AudioManager.InitAudio()
   at EQLogParser.AudioManager..ctor()
   at EQLogParser.AudioManager.<>c.<.cctor>b__32_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at EQLogParser.AudioManager.get_Instance()
   at EQLogParser.TriggerProcessor..ctor(String id, String name, String playerName, String voice, Int32 voiceRate, String activeColor, String fontColor, Action`4 addTextEvent, Action`3 addTimerEvent)
   at EQLogParser.TriggerManager.<>c__DisplayClass42_0.<<HandleAdvancedConfig>b__4>d.MoveNext()
--- End of stack trace from previous location ---
   at EQLogParser.TriggerManager.HandleAdvancedConfig(TriggerConfig config)
   at EQLogParser.TriggerManager.ConfigDoUpdate(Object sender, EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2024-08-20 19:42:21,974 [1] INFO EQLogParser.MainWindow - Finished Loading Log File in 2 seconds.
2024-08-20 19:42:52,011 [1] ERROR EQLogParser.App - DomainUnhandledException
System.IO.FileNotFoundException: Could not load file or assembly 'NAudio.WinForms, Version=2.2.1.0, Culture=neutral, PublicKeyToken=e279aa5131008a41'. The system cannot find the file specified.
File name: 'NAudio.WinForms, Version=2.2.1.0, Culture=neutral, PublicKeyToken=e279aa5131008a41'
   at EQLogParser.AudioManager.InitAudio()
   at EQLogParser.AudioManager..ctor()
   at EQLogParser.AudioManager.<>c.<.cctor>b__32_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at EQLogParser.AudioManager.get_Instance()
   at EQLogParser.TriggersView.VolumeButtonClick(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at EQLogParser.App.Main()
2024-08-20 19:43:04,869 [1] INFO EQLogParser.App - EQLogParser: 2.2.43, DotNet: 8.0.5
2024-08-20 19:43:04,891 [1] INFO EQLogParser.MainWindow - Window Pos (155, 3)
2024-08-20 19:43:04,891 [1] INFO EQLogParser.MainWindow - Window Size (1920, 811)
2024-08-20 19:43:09,228 [12] INFO EQLogParser.MainWindow - Selected Log File: C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\Logs\eqlog_Vaporizedx_xegony.txt
2024-08-20 19:43:10,439 [1] INFO EQLogParser.MainWindow - Finished Loading Log File in 1 seconds.
2024-08-20 19:43:10,734 [1] ERROR EQLogParser.App - AppDispatcherUnhandledException
System.IO.FileNotFoundException: Could not load file or assembly 'NAudio.WinForms, Version=2.2.1.0, Culture=neutral, PublicKeyToken=e279aa5131008a41'. The system cannot find the file specified.
File name: 'NAudio.WinForms, Version=2.2.1.0, Culture=neutral, PublicKeyToken=e279aa5131008a41'
   at EQLogParser.AudioManager.InitAudio()
   at EQLogParser.AudioManager..ctor()
   at EQLogParser.AudioManager.<>c.<.cctor>b__32_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at EQLogParser.AudioManager.get_Instance()
   at EQLogParser.TriggerProcessor..ctor(String id, String name, String playerName, String voice, Int32 voiceRate, String activeColor, String fontColor, Action`4 addTextEvent, Action`3 addTimerEvent)
   at EQLogParser.TriggerManager.<>c__DisplayClass42_0.<<HandleAdvancedConfig>b__4>d.MoveNext()
--- End of stack trace from previous location ---
   at EQLogParser.TriggerManager.HandleAdvancedConfig(TriggerConfig config)
   at EQLogParser.TriggerManager.ConfigDoUpdate(Object sender, EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by kauffman12** [comment]
Are you using remote desktop or something similar?

**Comment by vapourized** [comment]
I use take control to remote into other computers for my company but not running it while playing eq.

**Comment by kauffman12** [comment]
Ok here's one more to try and get logs for.

https://github.com/kauffman12/EQLogParser/raw/master/Release/test/EQLogParser-install-2.2.43-test3.exe

**Comment by vapourized** [comment]
Success for audio, at least I can test volume, and it does not crash.  I will have to test everything tonight when I have more time as my tells to speech is not working atm.



2024-08-21 05:55:00,539 [1] INFO EQLogParser.App - EQLogParser: 2.2.43, DotNet: 8.0.5
2024-08-21 05:55:00,869 [1] INFO EQLogParser.MainWindow - Window Pos (155, 3)
2024-08-21 05:55:00,869 [1] INFO EQLogParser.MainWindow - Window Size (1920, 811)
2024-08-21 05:55:09,073 [1] INFO EQLogParser.AudioManager - Init Audio
2024-08-21 05:55:09,108 [1] WARN EQLogParser.AudioManager - NEW API DOES WORK
2024-08-21 05:55:09,293 [1] INFO EQLogParser.AudioManager - Using audio device: Speakers (Realtek(R) Audio).
2024-08-21 05:55:09,546 [1] WARN EQLogParser.TriggerProcessor - Over 513 triggers active for one character. To improve performance consider turning off old triggers.
2024-08-21 06:17:13,157 [1] INFO EQLogParser.AudioManager - Init Audio
2024-08-21 06:17:13,174 [1] WARN EQLogParser.AudioManager - NEW API DOES WORK
2024-08-21 06:17:13,382 [1] INFO EQLogParser.AudioManager - Using audio device: Speakers (Realtek(R) Audio).
2024-08-21 06:17:40,762 [17] WARN EQLogParser.LogReader - Error Loading File: $C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\Logs\eqlog_Myysticall_xegony.txt. Re-open or toggle Triggers to try again.
2024-08-21 06:18:34,609 [1] WARN EQLogParser.TriggerProcessor - Over 513 triggers active for one character. To improve performance consider turning off old triggers.
2024-08-21 06:19:49,709 [1] WARN EQLogParser.TriggerProcessor - Over 513 triggers active for one character. To improve performance consider turning off old triggers.
2024-08-21 06:20:01,405 [1] WARN EQLogParser.TriggerProcessor - Over 513 triggers active for one character. To improve performance consider turning off old triggers.
2024-08-21 06:22:50,930 [1] WARN EQLogParser.TriggerProcessor - Over 513 triggers active for one character. To improve performance consider turning off old triggers.
2024-08-21 06:22:58,368 [1] WARN EQLogParser.TriggerProcessor - Over 513 triggers active for one character. To improve performance consider turning off old triggers.
2024-08-21 06:23:30,190 [31] INFO EQLogParser.AudioManager - Init Audio
2024-08-21 06:23:30,224 [31] WARN EQLogParser.AudioManager - NEW API DOES WORK
2024-08-21 06:23:30,425 [31] INFO EQLogParser.AudioManager - Using audio device: Speakers (Realtek(R) Audio).

**Comment by kauffman12** [comment]
I'll need to give you an update but that sounds good
