### ISSUE TITLE
Gina Share Expired

### ISSUE THREAD

**Issue by WaringMcMarrin** [kauffman12/EQLogParser#211]
I am regularly seeing the first share from Gina treats it as an expired share and I need to manually click on the share to import it. After the first share they seem to work as expected and a merge dialog box appears as expected.

**Comment by WaringMcMarrin** [comment]
This is what I see in the error log though I can click on the trigger share that errored out and import it right away.

024-11-05 20:04:43,978 [39] ERROR EQLogParser.GinaUtil - Error Downloading GINA Triggers
System.IO.InvalidDataException: The archive entry was compressed using an unsupported compression method.
   at System.IO.Compression.Inflater.Inflate(FlushCode flushCode)
   at System.IO.Compression.Inflater.ReadInflateOutput(Byte* bufPtr, Int32 length, FlushCode flushCode, Int32& bytesRead)
   at System.IO.Compression.Inflater.ReadOutput(Byte* bufPtr, Int32 length, Int32& bytesRead)
   at System.IO.Compression.Inflater.InflateVerified(Byte* bufPtr, Int32 length)
   at System.IO.Compression.DeflateStream.CopyToStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestination()
   at System.IO.Compression.DeflateStream.CopyTo(Stream destination, Int32 bufferSize)
   at EQLogParser.GinaUtil.<>c__DisplayClass8_0.<RunGinaTask>b__0(Task _)

**Comment by kauffman12** [comment]
I can't reproduce this one but I updated it to try a 2nd time on error so maybe that'll help. Try 2.2.50.

**Comment by WaringMcMarrin** [comment]
This change seems to have helped as I haven't seen the error since I updated my version
